**Data Extraction & Transformation (Python)**

**1. Source data loaded from CSV**

In [1]:
import pandas as pd
#Data frame _ 2D
#Pulling csv (comma separated values) file
restaurantdf = pd.read_csv(r"C:\Users\Tharaniya\Documents\GUVI\DS_Project1\Uber_Eats_data.csv",encoding='utf-8')
display(restaurantdf.head(10))

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
5,Timepass Dinner,Yes,No,3.8/5,286,+91 9980040002\r\n+91 9980063005,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,Buffet,Banashankari
6,Onesta,Yes,Yes,4.6/5,2556,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,Cafes,Banashankari
7,Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,Cafes,Banashankari
8,Smacznego,Yes,No,4.2/5,504,+91 9945230807\r\n+91 9743804471,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,Cafes,Banashankari
9,CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...,Yes,No,4.1/5,402,080 26724489\r\n+91 7406048982,Banashankari,Cafe,"Waffles, Pasta, Crispy Chicken, Honey Chilli C...",Cafe,500,Cafes,Banashankari

2 . Source data loaded from json

In [2]:
import pandas as pd
#Data frame _ 2D
#Pulling json  file
ordersdf = pd.read_json(r"C:\Users\Tharaniya\Documents\GUVI\DS_Project1\orders.json")
display(ordersdf.head(10))

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI
5,7d1b5f22-5bfd-42fd-90d1-4040a4aa8729,Cheesiano Pizza,2025-11-05,1179.90,No,Cash
6,96475dc3-1433-4792-8998-876b3efa6c59,Fullyfilled,2025-05-30,826.06,Yes,UPI
7,a2b66255-a6f7-4dcc-9a2b-45bf36e6da55,Bawarchi Inn,2025-12-26,1318.03,Yes,UPI
8,e44b23ce-6d29-4c09-9eac-9d4f24f56fd9,Sunny Cafe & Kitchen,2025-11-13,692.33,No,Cash
9,25b2d40b-35b3-40f7-9cbe-37bf690db837,Bathinda Junction,2025-12-08,455.51,No,Card

# Data cleaning

In [3]:
# Replaces the corrupted string with 'Cafe'
# Removes everything except letters (A-Z), numbers (0-9), and spaces
restaurantdf['name'] = restaurantdf['name'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)

display(restaurantdf.head(10))

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
5,Timepass Dinner,Yes,No,3.8/5,286,+91 9980040002\r\n+91 9980063005,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,Buffet,Banashankari
6,Onesta,Yes,Yes,4.6/5,2556,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,Cafes,Banashankari
7,Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,Cafes,Banashankari
8,Smacznego,Yes,No,4.2/5,504,+91 9945230807\r\n+91 9743804471,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,Cafes,Banashankari
9,Caf Down The Alley,Yes,No,4.1/5,402,080 26724489\r\n+91 7406048982,Banashankari,Cafe,"Waffles, Pasta, Crispy Chicken, Honey Chilli C...",Cafe,500,Cafes,Banashankari

In [4]:
# rename the existing  columns to meaning full names

restaurantdf.rename(columns={'name': 'restaurant_name'}, inplace=True)
restaurantdf.rename(columns={'approx_cost(for two people)': 'approx_two_person_cost'}, inplace=True)
restaurantdf.rename(columns={'listed_in(type)': 'category'}, inplace=True)
restaurantdf.rename(columns={'listed_in(city)': 'locality'}, inplace=True)
display(restaurantdf.head())

,restaurant_name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [5]:
# Finding the Duplicates sum
print(len(restaurantdf))
restaurantdf.duplicated().sum()

23193

np.int64(35)

In [6]:
# Finding the Duplicate rows
print(f"Number of duplicate sets (where at least one duplicate exists): {restaurantdf.duplicated(keep=False).sum()}")
display(restaurantdf[restaurantdf.duplicated(keep=False)].sort_values(['restaurant_name', 'locality']))

Number of duplicate sets (where at least one duplicate exists): 70

,restaurant_name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality
13845,154 Breakfast Club,Yes,Yes,4.0 /5,1515,080 25533133,Koramangala 3rd Block,Cafe,"Pancakes, Waffles, Bbq Sandwich, Mushroom Rago...","Cafe, Continental",900,Dine-out,Koramangala 5th Block
13846,154 Breakfast Club,Yes,Yes,4.0 /5,1515,080 25533133,Koramangala 3rd Block,Cafe,"Pancakes, Waffles, Bbq Sandwich, Mushroom Rago...","Cafe, Continental",900,Dine-out,Koramangala 5th Block
5118,99 Pancakes,Yes,No,4.1/5,41,+91 7483655827,Church Street,Dessert Parlor,Nutella Pancakes,"Desserts, Ice Cream",150,Delivery,Church Street
5417,99 Pancakes,Yes,No,4.1/5,41,+91 7483655827,Church Street,Dessert Parlor,Nutella Pancakes,"Desserts, Ice Cream",150,Delivery,Church Street
19692,Alchemy The Chancery Pavilion,No,Yes,4.3 /5,485,080 49653555,Residency Road,"Microbrewery, Casual Dining","Craft Beer, Cocktails, Stout, Chicken Wings, F...",Modern Indian,"2,000",Drinks & nightlife,MG Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8900,Toscano,Yes,Yes,4.5/5,715,080 22067757\r\n+91 7619320075,Koramangala 7th Block,Casual Dining,"Pizza, Pasta, Cocktails, Spinach Ravioli, Tira...","Italian, Salad","1,500",Delivery,Jayanagar
10761,Victoria Terminus,Yes,No,2.9/5,54,+91 9686933734\r\n+91 9066157771,Banaswadi,Quick Bites,"Vada Pav, Kulfi, Mumbai Sandwich, Rolls, Keema...","Fast Food, Maharashtrian, Rolls",250,Delivery,Kalyan Nagar
10763,Victoria Terminus,Yes,No,2.9/5,54,+91 9686933734\r\n+91 9066157771,Banaswadi,Quick Bites,"Vada Pav, Kulfi, Mumbai Sandwich, Rolls, Keema...","Fast Food, Maharashtrian, Rolls",250,Delivery,Kalyan Nagar
4238,Vyanjan,Yes,No,3.9/5,201,+91 9916937446,BTM,Quick Bites,"Poha, Jalebi, Paratha, Bhindi Masala, Kachori,...","North Indian, Street Food",300,Delivery,BTM
4243,Vyanjan,Yes,No,3.9/5,201,+91 9916937446,BTM,Quick Bites,"Poha, Jalebi, Paratha, Bhindi Masala, Kachori,...","North Indian, Street Food",300,Delivery,BTM

In [7]:
# Drop Duplicates
print(restaurantdf.duplicated().sum())
restaurantdf.drop_duplicates(inplace=True)
print(restaurantdf.duplicated().sum())

35
0

In [8]:
# Identifies the NULL values
restaurantdf.info() # There are no missing values or NULL values in the data set

<class 'pandas.core.frame.DataFrame'>
Index: 23158 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   restaurant_name         23158 non-null  object
 1   online_order            23158 non-null  object
 2   book_table              23158 non-null  object
 3   rate                    23158 non-null  object
 4   votes                   23158 non-null  int64
 5   phone                   23158 non-null  object
 6   location                23158 non-null  object
 7   rest_type               23158 non-null  object
 8   dish_liked              23158 non-null  object
 9   cuisines                23158 non-null  object
 10  approx_two_person_cost  23158 non-null  object
 11  category                23158 non-null  object
 12  locality                23158 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.5+ MB

In [9]:
# Splits  data "4.5/5" into ["4.5", "5"] and keeps "4.5"
restaurantdf['rate'] = restaurantdf['rate'].str.split('/').str[0]
restaurantdf

,restaurant_name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime Sheraton Grand Bengaluru Whitefield Hotel,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [10]:
# Find the Unique Rates
restaurantdf['rate'].unique()

array(['4.1', '3.8', '3.7', '4.6', '4.0', '4.2', '3.9', '3.0', '3.6',
       '2.8', '4.4', '3.1', '4.3', '2.6', '3.3', '3.5', '3.8 ', '3.2',
       '4.5', '2.5', '2.9', '3.4', '2.7', '4.7', 'NEW', '2.4', '2.2',
       '2.3', '4.8', '3.9 ', '4.2 ', '4.0 ', '4.1 ', '2.9 ', '2.7 ',
       '2.5 ', '2.6 ', '4.5 ', '4.3 ', '3.7 ', '4.4 ', '4.9', '2.1',
       '2.0', '1.8', '3.4 ', '3.6 ', '3.3 ', '4.6 ', '4.9 ', '3.2 ',
       '3.0 ', '2.8 ', '3.5 ', '3.1 ', '4.8 ', '2.3 ', '4.7 ', '2.4 ',
       '2.1 ', '2.2 ', '2.0 ', '1.8 '], dtype=object)

In [11]:
# Removes the spaces in the rate data
restaurantdf['rate'] = restaurantdf['rate'].str.strip()

In [12]:
# Replacing new with NULL values
restaurantdf['rate'] = restaurantdf['rate'].replace('NEW', pd.NA)
restaurantdf['rate'] = pd.to_numeric(restaurantdf['rate'], errors='coerce')
display(restaurantdf.head())

,restaurant_name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [13]:
# Converting rata data type into Float
restaurantdf['rate'] = restaurantdf['rate'].astype(float)

In [14]:
# Identifing the NULL values in the rows
restaurantdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23158 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   restaurant_name         23158 non-null  object
 1   online_order            23158 non-null  object
 2   book_table              23158 non-null  object
 3   rate                    23012 non-null  float64
 4   votes                   23158 non-null  int64
 5   phone                   23158 non-null  object
 6   location                23158 non-null  object
 7   rest_type               23158 non-null  object
 8   dish_liked              23158 non-null  object
 9   cuisines                23158 non-null  object
 10  approx_two_person_cost  23158 non-null  object
 11  category                23158 non-null  object
 12  locality                23158 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 2.5+ MB

In [15]:
# Removing comma in the cost data
restaurantdf["approx_two_person_cost"]=restaurantdf["approx_two_person_cost"].str.replace("," , "")
restaurantdf

,restaurant_name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,M Bar Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,Keys Cafe Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime Sheraton Grand Bengaluru Whitefield Hotel,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [16]:
# converting cost data type to int
restaurantdf["approx_two_person_cost"] = restaurantdf['approx_two_person_cost'].astype(int)
restaurantdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23158 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   restaurant_name         23158 non-null  object
 1   online_order            23158 non-null  object
 2   book_table              23158 non-null  object
 3   rate                    23012 non-null  float64
 4   votes                   23158 non-null  int64
 5   phone                   23158 non-null  object
 6   location                23158 non-null  object
 7   rest_type               23158 non-null  object
 8   dish_liked              23158 non-null  object
 9   cuisines                23158 non-null  object
 10  approx_two_person_cost  23158 non-null  int64
 11  category                23158 non-null  object
 12  locality                23158 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 2.5+ MB

In [17]:
# Spliting phone number into primary and secondary phone
a=restaurantdf["phone"].str.split("\n",expand=True) #converts
display(a)

                      0               1
0        080 42297555\r  +91 9743772233
1          080 41714161            None
2        +91 9663487993            None
3        +91 9620009302            None
4      +91 8026612447\r  +91 9901210005
...                 ...             ...
23188    +91 7625087121  +91 8050587483
23189      080 49435000            None
23190      080 39451000  +91 8884038484
23191      080 65951222            None
23192      080 49652769            None

[23158 rows x 2 columns]

In [18]:
#converts column datatype to string

restaurantdf["primary_phone"]=a[0].astype(str)
restaurantdf["secondary_phone"]=a[1].astype(str)
display(restaurantdf)

,restaurant_name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality,primary_phone,secondary_phone
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,080 42297555\r,+91 9743772233
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,080 41714161,None
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,+91 9663487993,None
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,+91 9620009302,None
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,+91 8026612447\r,+91 9901210005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield,+91 7625087121,+91 8050587483
23189,M Bar Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield,080 49435000,None
23190,Keys Cafe Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield,080 39451000,+91 8884038484
23191,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield,080 65951222,None
23192,Chime Sheraton Grand Bengaluru Whitefield Hotel,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield,080 49652769,None

In [19]:
# Drop the phone column
restaurantdf.drop("phone",axis=1,inplace=True)#drop column permanently
display(restaurantdf)

,restaurant_name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality,primary_phone,secondary_phone
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,080 42297555\r,+91 9743772233
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,080 41714161,None
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,+91 9663487993,None
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,+91 9620009302,None
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,+91 8026612447\r,+91 9901210005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield,+91 7625087121,+91 8050587483
23189,M Bar Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield,080 49435000,None
23190,Keys Cafe Keys Hotel,No,No,2.8,161,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield,080 39451000,+91 8884038484
23191,Bhagini,No,No,2.5,81,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield,080 65951222,None
23192,Chime Sheraton Grand Bengaluru Whitefield Hotel,No,Yes,4.3,236,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield,080 49652769,None

In [20]:
# Specify the new order
new_order = ['restaurant_name', 'primary_phone', 'secondary_phone','location', 'online_order', 'book_table', 'rate', 'votes', 'rest_type', 'dish_liked', 'cuisines', 'approx_two_person_cost', 'category', 'locality']
restaurantdf = restaurantdf[new_order]
display(restaurantdf)

,restaurant_name,primary_phone,secondary_phone,location,online_order,book_table,rate,votes,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality
0,Jalsa,080 42297555\r,+91 9743772233,Banashankari,Yes,Yes,4.1,775,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,080 41714161,None,Banashankari,Yes,No,4.1,787,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,+91 9663487993,None,Banashankari,Yes,No,3.8,918,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,+91 9620009302,None,Banashankari,No,No,3.7,88,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,+91 8026612447\r,+91 9901210005,Basavanagudi,No,No,3.8,166,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,+91 7625087121,+91 8050587483,Whitefield,Yes,Yes,3.8,128,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,M Bar Bengaluru Marriott Hotel Whitefield,080 49435000,None,Whitefield,No,No,3.9,77,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,Keys Cafe Keys Hotel,080 39451000,+91 8884038484,Whitefield,No,No,2.8,161,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,Bhagini,080 65951222,None,Whitefield,No,No,2.5,81,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime Sheraton Grand Bengaluru Whitefield Hotel,080 49652769,None,"ITPL Main Road, Whitefield",No,Yes,4.3,236,Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [21]:
# removing \r from the data
restaurantdf["primary_phone"]=restaurantdf["primary_phone"].str.replace("\r" , "")
restaurantdf

,restaurant_name,primary_phone,secondary_phone,location,online_order,book_table,rate,votes,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality
0,Jalsa,080 42297555,+91 9743772233,Banashankari,Yes,Yes,4.1,775,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,080 41714161,None,Banashankari,Yes,No,4.1,787,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,+91 9663487993,None,Banashankari,Yes,No,3.8,918,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,+91 9620009302,None,Banashankari,No,No,3.7,88,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,+91 8026612447,+91 9901210005,Basavanagudi,No,No,3.8,166,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,+91 7625087121,+91 8050587483,Whitefield,Yes,Yes,3.8,128,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,M Bar Bengaluru Marriott Hotel Whitefield,080 49435000,None,Whitefield,No,No,3.9,77,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,Keys Cafe Keys Hotel,080 39451000,+91 8884038484,Whitefield,No,No,2.8,161,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,Bhagini,080 65951222,None,Whitefield,No,No,2.5,81,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime Sheraton Grand Bengaluru Whitefield Hotel,080 49652769,None,"ITPL Main Road, Whitefield",No,Yes,4.3,236,Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [22]:
# Creates a column 'id' from 1 to the total number of rows
restaurantdf.insert(0, 'restaurant_id', range(1, 1 + len(restaurantdf)))
restaurantdf

,restaurant_id,restaurant_name,primary_phone,secondary_phone,location,online_order,book_table,rate,votes,rest_type,dish_liked,cuisines,approx_two_person_cost,category,locality
0,1,Jalsa,080 42297555,+91 9743772233,Banashankari,Yes,Yes,4.1,775,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,2,Spice Elephant,080 41714161,None,Banashankari,Yes,No,4.1,787,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,3,San Churro Cafe,+91 9663487993,None,Banashankari,Yes,No,3.8,918,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,4,Addhuri Udupi Bhojana,+91 9620009302,None,Banashankari,No,No,3.7,88,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,5,Grand Village,+91 8026612447,+91 9901210005,Basavanagudi,No,No,3.8,166,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,23154,Izakaya Gastro Pub,+91 7625087121,+91 8050587483,Whitefield,Yes,Yes,3.8,128,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,23155,M Bar Bengaluru Marriott Hotel Whitefield,080 49435000,None,Whitefield,No,No,3.9,77,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,23156,Keys Cafe Keys Hotel,080 39451000,+91 8884038484,Whitefield,No,No,2.8,161,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,23157,Bhagini,080 65951222,None,Whitefield,No,No,2.5,81,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,23158,Chime Sheraton Grand Bengaluru Whitefield Hotel,080 49652769,None,"ITPL Main Road, Whitefield",No,Yes,4.3,236,Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [23]:
# Removing unvanted characters
ordersdf['restaurant_name'] = ordersdf['restaurant_name'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)

display(ordersdf.head(10))

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI
5,7d1b5f22-5bfd-42fd-90d1-4040a4aa8729,Cheesiano Pizza,2025-11-05,1179.90,No,Cash
6,96475dc3-1433-4792-8998-876b3efa6c59,Fullyfilled,2025-05-30,826.06,Yes,UPI
7,a2b66255-a6f7-4dcc-9a2b-45bf36e6da55,Bawarchi Inn,2025-12-26,1318.03,Yes,UPI
8,e44b23ce-6d29-4c09-9eac-9d4f24f56fd9,Sunny Cafe Kitchen,2025-11-13,692.33,No,Cash
9,25b2d40b-35b3-40f7-9cbe-37bf690db837,Bathinda Junction,2025-12-08,455.51,No,Card

# Load the data into sqlite

In [24]:
import sqlite3
import pandas as pd

# 1. Create a connection to the database (it creates the file if it doesn't exist)
conn = sqlite3.connect('ubereats_data.db')

# 2. Write the DataFrame to a table
restaurantdf.to_sql('restaurants', conn, if_exists='replace', index=False)

ordersdf.to_sql('orders', conn, if_exists='replace', index=False)

# 3. Close the connection
conn.close()

# Checking the Data in the Database

In [25]:
import sqlite3
import pandas as pd

# Connect to your database
conn = sqlite3.connect('ubereats_data.db')

# Query the first 10 rows
query = "SELECT * FROM restaurants LIMIT 10"
df_result = pd.read_sql_query(query, conn)

print(df_result)

   restaurant_id        restaurant_name   primary_phone secondary_phone  \
0              1                  Jalsa    080 42297555  +91 9743772233
1              2         Spice Elephant    080 41714161            None
2              3        San Churro Cafe  +91 9663487993            None
3              4  Addhuri Udupi Bhojana  +91 9620009302            None
4              5          Grand Village  +91 8026612447  +91 9901210005
5              6        Timepass Dinner  +91 9980040002  +91 9980063005
6              7                 Onesta    080 48653961    080 48655715
7              8         Penthouse Cafe  +91 8884135549  +91 9449449316
8              9              Smacznego  +91 9945230807  +91 9743804471
9             10     Caf Down The Alley    080 26724489  +91 7406048982

       location online_order book_table  rate  votes            rest_type  \
0  Banashankari          Yes        Yes   4.1    775        Casual Dining
1  Banashankari          Yes         No   4.1    787        Casual Dining
2  Banashankari          Yes         No   3.8    918  Cafe, Casual Dining
3  Banashankari           No         No   3.7     88          Quick Bites
4  Basavanagudi           No         No   3.8    166        Casual Dining
5  Basavanagudi          Yes         No   3.8    286        Casual Dining
6  Banashankari          Yes        Yes   4.6   2556  Casual Dining, Cafe
7  Banashankari          Yes         No   4.0    324                 Cafe
8  Banashankari          Yes         No   4.2    504                 Cafe
9  Banashankari          Yes         No   4.1    402                 Cafe

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2  Churros, Cannelloni, Minestrone Soup, Hot Choc...
3                                        Masala Dosa
4                                Panipuri, Gol Gappe
5  Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...
6  Farmhouse Pizza, Chocolate Banana, Virgin Moji...
7  Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...
8  Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...
9  Waffles, Pasta, Crispy Chicken, Honey Chilli C...

                                   cuisines  approx_two_person_cost category  \
0            North Indian, Mughlai, Chinese                     800   Buffet
1               Chinese, North Indian, Thai                     800   Buffet
2                    Cafe, Mexican, Italian                     800   Buffet
3                South Indian, North Indian                     300   Buffet
4                  North Indian, Rajasthani                     600   Buffet
5                              North Indian                     600   Buffet
6                      Pizza, Cafe, Italian                     600    Cafes
7                Cafe, Italian, Continental                     700    Cafes
8  Cafe, Mexican, Italian, Momos, Beverages                     550    Cafes
9                                      Cafe                     500    Cafes

       locality
0  Banashankari
1  Banashankari
2  Banashankari
3  Banashankari
4  Banashankari
5  Banashankari
6  Banashankari
7  Banashankari
8  Banashankari
9  Banashankari